apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-orders.fullname" . }}
  labels:
    {{- include "mysql-orders.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "mysql-orders.fullname" . }}-headless"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mysql-orders.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "mysql-orders.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql-orders
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-orders-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-orders-data
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
