apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamodb.fullname" . }}
  labels:
    {{- include "dynamodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: dynamodb
      protocol: TCP
      name: dynamodb
  selector:
    app: {{ include "dynamodb.name" . }}
    release: {{ .Release.Name }}
