apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dynamodb.fullname" . }}
  labels:
    {{- include "dynamodb.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "dynamodb.fullname" . }}-headless"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dynamodb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "dynamodb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: dynamodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: dynamodb
          volumeMounts:
            - name: dynamodb-data
              mountPath: /home/dynamodblocal/data
  volumeClaimTemplates:
    - metadata:
        name: dynamodb-data
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
