apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolumes.name }}
  labels:
    app: catalog-db
spec:
  capacity:
    storage: {{ .Values.persistentVolumes.capacity }}
  accessModes:
    {{- toYaml .Values.persistentVolumes.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.persistentVolumes.hostPath.path }}
