apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog-db.fullname" . }}
  labels:
    {{- include "catalog-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: {{ include "catalog-db.name" . }}
    release: {{ .Release.Name }}
