image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: Always

replicaCount: 1

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  storageClass: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistentVolumes:
  name: pv-rabbitmq
  capacity: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /mnt/data/rabbitmq
